/*------------------------------------------------------------------------------
//   This code was generated by template ffi_gdextension_interface.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_gdextension_interface.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/
package ffi

//revive:disable

var (
	api GDExtensionInterface
)

type GDExtensionInterface struct {
	// All of the GDExtension interface functions.
	SpxGlobalRegisterCallbacks GDExtensionSpxGlobalRegisterCallbacks
	SpxStringNewWithLatin1Chars GDExtensionSpxStringNewWithLatin1Chars
	SpxStringNewWithUtf8Chars GDExtensionSpxStringNewWithUtf8Chars
	SpxStringNewWithLatin1CharsAndLen GDExtensionSpxStringNewWithLatin1CharsAndLen
	SpxStringNewWithUtf8CharsAndLen GDExtensionSpxStringNewWithUtf8CharsAndLen
	SpxStringToLatin1Chars GDExtensionSpxStringToLatin1Chars
	SpxStringToUtf8Chars GDExtensionSpxStringToUtf8Chars
	SpxVariantGetPtrConstructor GDExtensionSpxVariantGetPtrConstructor
	SpxVariantGetPtrDestructor GDExtensionSpxVariantGetPtrDestructor
	SpxAudioPlayAudio GDExtensionSpxAudioPlayAudio
	SpxAudioSetAudioVolume GDExtensionSpxAudioSetAudioVolume
	SpxAudioGetAudioVolume GDExtensionSpxAudioGetAudioVolume
	SpxAudioIsMusicPlaying GDExtensionSpxAudioIsMusicPlaying
	SpxAudioPlayMusic GDExtensionSpxAudioPlayMusic
	SpxAudioSetMusicVolume GDExtensionSpxAudioSetMusicVolume
	SpxAudioGetMusicVolume GDExtensionSpxAudioGetMusicVolume
	SpxAudioPauseMusic GDExtensionSpxAudioPauseMusic
	SpxAudioResumeMusic GDExtensionSpxAudioResumeMusic
	SpxAudioGetMusicTimer GDExtensionSpxAudioGetMusicTimer
	SpxAudioSetMusicTimer GDExtensionSpxAudioSetMusicTimer
	SpxInputGetMousePos GDExtensionSpxInputGetMousePos
	SpxInputGetMouseState GDExtensionSpxInputGetMouseState
	SpxInputGetKeyState GDExtensionSpxInputGetKeyState
	SpxInputGetAxis GDExtensionSpxInputGetAxis
	SpxInputIsActionPressed GDExtensionSpxInputIsActionPressed
	SpxInputIsActionJustPressed GDExtensionSpxInputIsActionJustPressed
	SpxInputIsActionJustReleased GDExtensionSpxInputIsActionJustReleased
	SpxPhysicSetGravity GDExtensionSpxPhysicSetGravity
	SpxPhysicGetGravity GDExtensionSpxPhysicGetGravity
	SpxPhysicSetVelocity GDExtensionSpxPhysicSetVelocity
	SpxPhysicGetVelocity GDExtensionSpxPhysicGetVelocity
	SpxPhysicSetMass GDExtensionSpxPhysicSetMass
	SpxPhysicGetMass GDExtensionSpxPhysicGetMass
	SpxPhysicAddForce GDExtensionSpxPhysicAddForce
	SpxPhysicAddImpulse GDExtensionSpxPhysicAddImpulse
	SpxPhysicSetCollisionLayer GDExtensionSpxPhysicSetCollisionLayer
	SpxPhysicGetCollisionLayer GDExtensionSpxPhysicGetCollisionLayer
	SpxPhysicSetCollisionMask GDExtensionSpxPhysicSetCollisionMask
	SpxPhysicGetCollisionMask GDExtensionSpxPhysicGetCollisionMask
	SpxPhysicGetColliderType GDExtensionSpxPhysicGetColliderType
	SpxPhysicAddColliderRect GDExtensionSpxPhysicAddColliderRect
	SpxPhysicAddColliderCircle GDExtensionSpxPhysicAddColliderCircle
	SpxPhysicAddColliderCapsule GDExtensionSpxPhysicAddColliderCapsule
	SpxPhysicSetTrigger GDExtensionSpxPhysicSetTrigger
	SpxPhysicIsTrigger GDExtensionSpxPhysicIsTrigger
	SpxPhysicSetCollisionEnabled GDExtensionSpxPhysicSetCollisionEnabled
	SpxPhysicIsCollisionEnabled GDExtensionSpxPhysicIsCollisionEnabled
	SpxSpriteCreateSprite GDExtensionSpxSpriteCreateSprite
	SpxSpriteCloneSprite GDExtensionSpxSpriteCloneSprite
	SpxSpriteDestroySprite GDExtensionSpxSpriteDestroySprite
	SpxSpriteIsSpriteAlive GDExtensionSpxSpriteIsSpriteAlive
	SpxSpriteSetPosition GDExtensionSpxSpriteSetPosition
	SpxSpriteSetRotation GDExtensionSpxSpriteSetRotation
	SpxSpriteSetScale GDExtensionSpxSpriteSetScale
	SpxSpriteGetPosition GDExtensionSpxSpriteGetPosition
	SpxSpriteGetRotation GDExtensionSpxSpriteGetRotation
	SpxSpriteGetScale GDExtensionSpxSpriteGetScale
	SpxSpriteSetColor GDExtensionSpxSpriteSetColor
	SpxSpriteGetColor GDExtensionSpxSpriteGetColor
	SpxSpriteUpdateTexture GDExtensionSpxSpriteUpdateTexture
	SpxSpriteGetTexture GDExtensionSpxSpriteGetTexture
	SpxSpriteSetVisible GDExtensionSpxSpriteSetVisible
	SpxSpriteGetVisible GDExtensionSpxSpriteGetVisible
	SpxSpriteUpdateZIndex GDExtensionSpxSpriteUpdateZIndex
	SpxUICreateButton GDExtensionSpxUICreateButton
	SpxUICreateLabel GDExtensionSpxUICreateLabel
	SpxUICreateImage GDExtensionSpxUICreateImage
	SpxUICreateSlider GDExtensionSpxUICreateSlider
	SpxUICreateToggle GDExtensionSpxUICreateToggle
	SpxUICreateInput GDExtensionSpxUICreateInput
	SpxUIGetType GDExtensionSpxUIGetType
	SpxUISetInteractable GDExtensionSpxUISetInteractable
	SpxUIGetInteractable GDExtensionSpxUIGetInteractable
	SpxUISetText GDExtensionSpxUISetText
	SpxUIGetText GDExtensionSpxUIGetText
	SpxUISetRect GDExtensionSpxUISetRect
	SpxUIGetRect GDExtensionSpxUIGetRect
	SpxUISetColor GDExtensionSpxUISetColor
	SpxUIGetColor GDExtensionSpxUIGetColor
	SpxUISetFontSize GDExtensionSpxUISetFontSize
	SpxUIGetFontSize GDExtensionSpxUIGetFontSize
	SpxUISetVisible GDExtensionSpxUISetVisible
	SpxUIGetVisible GDExtensionSpxUIGetVisible
	}

func (x *GDExtensionInterface) loadProcAddresses() {

	x.SpxGlobalRegisterCallbacks = (GDExtensionSpxGlobalRegisterCallbacks)(dlsymGD("spx_global_register_callbacks"))
	x.SpxStringNewWithLatin1Chars = (GDExtensionSpxStringNewWithLatin1Chars)(dlsymGD("spx_string_new_with_latin1_chars"))
	x.SpxStringNewWithUtf8Chars = (GDExtensionSpxStringNewWithUtf8Chars)(dlsymGD("spx_string_new_with_utf8_chars"))
	x.SpxStringNewWithLatin1CharsAndLen = (GDExtensionSpxStringNewWithLatin1CharsAndLen)(dlsymGD("spx_string_new_with_latin1_chars_and_len"))
	x.SpxStringNewWithUtf8CharsAndLen = (GDExtensionSpxStringNewWithUtf8CharsAndLen)(dlsymGD("spx_string_new_with_utf8_chars_and_len"))
	x.SpxStringToLatin1Chars = (GDExtensionSpxStringToLatin1Chars)(dlsymGD("spx_string_to_latin1_chars"))
	x.SpxStringToUtf8Chars = (GDExtensionSpxStringToUtf8Chars)(dlsymGD("spx_string_to_utf8_chars"))
	x.SpxVariantGetPtrConstructor = (GDExtensionSpxVariantGetPtrConstructor)(dlsymGD("spx_variant_get_ptr_constructor"))
	x.SpxVariantGetPtrDestructor = (GDExtensionSpxVariantGetPtrDestructor)(dlsymGD("spx_variant_get_ptr_destructor"))
	x.SpxAudioPlayAudio = (GDExtensionSpxAudioPlayAudio)(dlsymGD("spx_audio_play_audio"))
	x.SpxAudioSetAudioVolume = (GDExtensionSpxAudioSetAudioVolume)(dlsymGD("spx_audio_set_audio_volume"))
	x.SpxAudioGetAudioVolume = (GDExtensionSpxAudioGetAudioVolume)(dlsymGD("spx_audio_get_audio_volume"))
	x.SpxAudioIsMusicPlaying = (GDExtensionSpxAudioIsMusicPlaying)(dlsymGD("spx_audio_is_music_playing"))
	x.SpxAudioPlayMusic = (GDExtensionSpxAudioPlayMusic)(dlsymGD("spx_audio_play_music"))
	x.SpxAudioSetMusicVolume = (GDExtensionSpxAudioSetMusicVolume)(dlsymGD("spx_audio_set_music_volume"))
	x.SpxAudioGetMusicVolume = (GDExtensionSpxAudioGetMusicVolume)(dlsymGD("spx_audio_get_music_volume"))
	x.SpxAudioPauseMusic = (GDExtensionSpxAudioPauseMusic)(dlsymGD("spx_audio_pause_music"))
	x.SpxAudioResumeMusic = (GDExtensionSpxAudioResumeMusic)(dlsymGD("spx_audio_resume_music"))
	x.SpxAudioGetMusicTimer = (GDExtensionSpxAudioGetMusicTimer)(dlsymGD("spx_audio_get_music_timer"))
	x.SpxAudioSetMusicTimer = (GDExtensionSpxAudioSetMusicTimer)(dlsymGD("spx_audio_set_music_timer"))
	x.SpxInputGetMousePos = (GDExtensionSpxInputGetMousePos)(dlsymGD("spx_input_get_mouse_pos"))
	x.SpxInputGetMouseState = (GDExtensionSpxInputGetMouseState)(dlsymGD("spx_input_get_mouse_state"))
	x.SpxInputGetKeyState = (GDExtensionSpxInputGetKeyState)(dlsymGD("spx_input_get_key_state"))
	x.SpxInputGetAxis = (GDExtensionSpxInputGetAxis)(dlsymGD("spx_input_get_axis"))
	x.SpxInputIsActionPressed = (GDExtensionSpxInputIsActionPressed)(dlsymGD("spx_input_is_action_pressed"))
	x.SpxInputIsActionJustPressed = (GDExtensionSpxInputIsActionJustPressed)(dlsymGD("spx_input_is_action_just_pressed"))
	x.SpxInputIsActionJustReleased = (GDExtensionSpxInputIsActionJustReleased)(dlsymGD("spx_input_is_action_just_released"))
	x.SpxPhysicSetGravity = (GDExtensionSpxPhysicSetGravity)(dlsymGD("spx_physic_set_gravity"))
	x.SpxPhysicGetGravity = (GDExtensionSpxPhysicGetGravity)(dlsymGD("spx_physic_get_gravity"))
	x.SpxPhysicSetVelocity = (GDExtensionSpxPhysicSetVelocity)(dlsymGD("spx_physic_set_velocity"))
	x.SpxPhysicGetVelocity = (GDExtensionSpxPhysicGetVelocity)(dlsymGD("spx_physic_get_velocity"))
	x.SpxPhysicSetMass = (GDExtensionSpxPhysicSetMass)(dlsymGD("spx_physic_set_mass"))
	x.SpxPhysicGetMass = (GDExtensionSpxPhysicGetMass)(dlsymGD("spx_physic_get_mass"))
	x.SpxPhysicAddForce = (GDExtensionSpxPhysicAddForce)(dlsymGD("spx_physic_add_force"))
	x.SpxPhysicAddImpulse = (GDExtensionSpxPhysicAddImpulse)(dlsymGD("spx_physic_add_impulse"))
	x.SpxPhysicSetCollisionLayer = (GDExtensionSpxPhysicSetCollisionLayer)(dlsymGD("spx_physic_set_collision_layer"))
	x.SpxPhysicGetCollisionLayer = (GDExtensionSpxPhysicGetCollisionLayer)(dlsymGD("spx_physic_get_collision_layer"))
	x.SpxPhysicSetCollisionMask = (GDExtensionSpxPhysicSetCollisionMask)(dlsymGD("spx_physic_set_collision_mask"))
	x.SpxPhysicGetCollisionMask = (GDExtensionSpxPhysicGetCollisionMask)(dlsymGD("spx_physic_get_collision_mask"))
	x.SpxPhysicGetColliderType = (GDExtensionSpxPhysicGetColliderType)(dlsymGD("spx_physic_get_collider_type"))
	x.SpxPhysicAddColliderRect = (GDExtensionSpxPhysicAddColliderRect)(dlsymGD("spx_physic_add_collider_rect"))
	x.SpxPhysicAddColliderCircle = (GDExtensionSpxPhysicAddColliderCircle)(dlsymGD("spx_physic_add_collider_circle"))
	x.SpxPhysicAddColliderCapsule = (GDExtensionSpxPhysicAddColliderCapsule)(dlsymGD("spx_physic_add_collider_capsule"))
	x.SpxPhysicSetTrigger = (GDExtensionSpxPhysicSetTrigger)(dlsymGD("spx_physic_set_trigger"))
	x.SpxPhysicIsTrigger = (GDExtensionSpxPhysicIsTrigger)(dlsymGD("spx_physic_is_trigger"))
	x.SpxPhysicSetCollisionEnabled = (GDExtensionSpxPhysicSetCollisionEnabled)(dlsymGD("spx_physic_set_collision_enabled"))
	x.SpxPhysicIsCollisionEnabled = (GDExtensionSpxPhysicIsCollisionEnabled)(dlsymGD("spx_physic_is_collision_enabled"))
	x.SpxSpriteCreateSprite = (GDExtensionSpxSpriteCreateSprite)(dlsymGD("spx_sprite_create_sprite"))
	x.SpxSpriteCloneSprite = (GDExtensionSpxSpriteCloneSprite)(dlsymGD("spx_sprite_clone_sprite"))
	x.SpxSpriteDestroySprite = (GDExtensionSpxSpriteDestroySprite)(dlsymGD("spx_sprite_destroy_sprite"))
	x.SpxSpriteIsSpriteAlive = (GDExtensionSpxSpriteIsSpriteAlive)(dlsymGD("spx_sprite_is_sprite_alive"))
	x.SpxSpriteSetPosition = (GDExtensionSpxSpriteSetPosition)(dlsymGD("spx_sprite_set_position"))
	x.SpxSpriteSetRotation = (GDExtensionSpxSpriteSetRotation)(dlsymGD("spx_sprite_set_rotation"))
	x.SpxSpriteSetScale = (GDExtensionSpxSpriteSetScale)(dlsymGD("spx_sprite_set_scale"))
	x.SpxSpriteGetPosition = (GDExtensionSpxSpriteGetPosition)(dlsymGD("spx_sprite_get_position"))
	x.SpxSpriteGetRotation = (GDExtensionSpxSpriteGetRotation)(dlsymGD("spx_sprite_get_rotation"))
	x.SpxSpriteGetScale = (GDExtensionSpxSpriteGetScale)(dlsymGD("spx_sprite_get_scale"))
	x.SpxSpriteSetColor = (GDExtensionSpxSpriteSetColor)(dlsymGD("spx_sprite_set_color"))
	x.SpxSpriteGetColor = (GDExtensionSpxSpriteGetColor)(dlsymGD("spx_sprite_get_color"))
	x.SpxSpriteUpdateTexture = (GDExtensionSpxSpriteUpdateTexture)(dlsymGD("spx_sprite_update_texture"))
	x.SpxSpriteGetTexture = (GDExtensionSpxSpriteGetTexture)(dlsymGD("spx_sprite_get_texture"))
	x.SpxSpriteSetVisible = (GDExtensionSpxSpriteSetVisible)(dlsymGD("spx_sprite_set_visible"))
	x.SpxSpriteGetVisible = (GDExtensionSpxSpriteGetVisible)(dlsymGD("spx_sprite_get_visible"))
	x.SpxSpriteUpdateZIndex = (GDExtensionSpxSpriteUpdateZIndex)(dlsymGD("spx_sprite_update_z_index"))
	x.SpxUICreateButton = (GDExtensionSpxUICreateButton)(dlsymGD("spx_ui_create_button"))
	x.SpxUICreateLabel = (GDExtensionSpxUICreateLabel)(dlsymGD("spx_ui_create_label"))
	x.SpxUICreateImage = (GDExtensionSpxUICreateImage)(dlsymGD("spx_ui_create_image"))
	x.SpxUICreateSlider = (GDExtensionSpxUICreateSlider)(dlsymGD("spx_ui_create_slider"))
	x.SpxUICreateToggle = (GDExtensionSpxUICreateToggle)(dlsymGD("spx_ui_create_toggle"))
	x.SpxUICreateInput = (GDExtensionSpxUICreateInput)(dlsymGD("spx_ui_create_input"))
	x.SpxUIGetType = (GDExtensionSpxUIGetType)(dlsymGD("spx_ui_get_type"))
	x.SpxUISetInteractable = (GDExtensionSpxUISetInteractable)(dlsymGD("spx_ui_set_interactable"))
	x.SpxUIGetInteractable = (GDExtensionSpxUIGetInteractable)(dlsymGD("spx_ui_get_interactable"))
	x.SpxUISetText = (GDExtensionSpxUISetText)(dlsymGD("spx_ui_set_text"))
	x.SpxUIGetText = (GDExtensionSpxUIGetText)(dlsymGD("spx_ui_get_text"))
	x.SpxUISetRect = (GDExtensionSpxUISetRect)(dlsymGD("spx_ui_set_rect"))
	x.SpxUIGetRect = (GDExtensionSpxUIGetRect)(dlsymGD("spx_ui_get_rect"))
	x.SpxUISetColor = (GDExtensionSpxUISetColor)(dlsymGD("spx_ui_set_color"))
	x.SpxUIGetColor = (GDExtensionSpxUIGetColor)(dlsymGD("spx_ui_get_color"))
	x.SpxUISetFontSize = (GDExtensionSpxUISetFontSize)(dlsymGD("spx_ui_set_font_size"))
	x.SpxUIGetFontSize = (GDExtensionSpxUIGetFontSize)(dlsymGD("spx_ui_get_font_size"))
	x.SpxUISetVisible = (GDExtensionSpxUISetVisible)(dlsymGD("spx_ui_set_visible"))
	x.SpxUIGetVisible = (GDExtensionSpxUIGetVisible)(dlsymGD("spx_ui_get_visible"))
	}
