/*------------------------------------------------------------------------------
//   This code was generated by template ffi_wrapper.c.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_wrapper.h.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/
#include "gdextension_spx_codegen_header.h"
#include "ffi_wrapper.gen.h"

/* Go cannot call C function pointers directly, so we must generate C wrapper code to call the functions. */

void cgo_callfn_GDExtensionSpxGlobalRegisterCallbacks(const GDExtensionSpxGlobalRegisterCallbacks fn, GDExtensionSpxCallbackInfoPtr callback_ptr) {
		//printStacktrace();
		 fn(callback_ptr);
	}
gdvec2 cgo_callfn_GDExtensionSpxInputGetMousePos(const GDExtensionSpxInputGetMousePos fn) {
		//printStacktrace();
		return fn();
	}
gdbool cgo_callfn_GDExtensionSpxInputGetMouseState(const GDExtensionSpxInputGetMouseState fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
gdint cgo_callfn_GDExtensionSpxInputGetKeyState(const GDExtensionSpxInputGetKeyState fn, gdint key) {
		//printStacktrace();
		return fn(key);
	}
gdfloat cgo_callfn_GDExtensionSpxInputGetAxis(const GDExtensionSpxInputGetAxis fn, gdstring axis) {
		//printStacktrace();
		return fn(axis);
	}
gdbool cgo_callfn_GDExtensionSpxInputIsActionPressed(const GDExtensionSpxInputIsActionPressed fn, gdstring action) {
		//printStacktrace();
		return fn(action);
	}
gdbool cgo_callfn_GDExtensionSpxInputIsActionJustPressed(const GDExtensionSpxInputIsActionJustPressed fn, gdstring action) {
		//printStacktrace();
		return fn(action);
	}
gdbool cgo_callfn_GDExtensionSpxInputIsActionJustReleased(const GDExtensionSpxInputIsActionJustReleased fn, gdstring action) {
		//printStacktrace();
		return fn(action);
	}
void cgo_callfn_GDExtensionSpxAudioPlayAudio(const GDExtensionSpxAudioPlayAudio fn, gdstring path) {
		//printStacktrace();
		 fn(path);
	}
void cgo_callfn_GDExtensionSpxAudioSetAudioVolume(const GDExtensionSpxAudioSetAudioVolume fn, gdfloat volume) {
		//printStacktrace();
		 fn(volume);
	}
gdfloat cgo_callfn_GDExtensionSpxAudioGetAudioVolume(const GDExtensionSpxAudioGetAudioVolume fn) {
		//printStacktrace();
		return fn();
	}
gdbool cgo_callfn_GDExtensionSpxAudioIsMusicPlaying(const GDExtensionSpxAudioIsMusicPlaying fn) {
		//printStacktrace();
		return fn();
	}
void cgo_callfn_GDExtensionSpxAudioPlayMusic(const GDExtensionSpxAudioPlayMusic fn, gdstring path) {
		//printStacktrace();
		 fn(path);
	}
void cgo_callfn_GDExtensionSpxAudioSetMusicVolume(const GDExtensionSpxAudioSetMusicVolume fn, gdfloat volume) {
		//printStacktrace();
		 fn(volume);
	}
gdfloat cgo_callfn_GDExtensionSpxAudioGetMusicVolume(const GDExtensionSpxAudioGetMusicVolume fn) {
		//printStacktrace();
		return fn();
	}
void cgo_callfn_GDExtensionSpxAudioPauseMusic(const GDExtensionSpxAudioPauseMusic fn) {
		//printStacktrace();
		 fn();
	}
void cgo_callfn_GDExtensionSpxAudioResumeMusic(const GDExtensionSpxAudioResumeMusic fn) {
		//printStacktrace();
		 fn();
	}
gdfloat cgo_callfn_GDExtensionSpxAudioGetMusicTimer(const GDExtensionSpxAudioGetMusicTimer fn) {
		//printStacktrace();
		return fn();
	}
void cgo_callfn_GDExtensionSpxAudioSetMusicTimer(const GDExtensionSpxAudioSetMusicTimer fn, gdfloat time) {
		//printStacktrace();
		 fn(time);
	}
void cgo_callfn_GDExtensionSpxPhysicSetGravity(const GDExtensionSpxPhysicSetGravity fn, gdfloat gravity) {
		//printStacktrace();
		 fn(gravity);
	}
gdfloat cgo_callfn_GDExtensionSpxPhysicGetGravity(const GDExtensionSpxPhysicGetGravity fn) {
		//printStacktrace();
		return fn();
	}
void cgo_callfn_GDExtensionSpxPhysicSetVelocity(const GDExtensionSpxPhysicSetVelocity fn, gdint id, gdvec2 velocity) {
		//printStacktrace();
		 fn(id, velocity);
	}
gdvec2 cgo_callfn_GDExtensionSpxPhysicGetVelocity(const GDExtensionSpxPhysicGetVelocity fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxPhysicSetMass(const GDExtensionSpxPhysicSetMass fn, gdint id, gdfloat mass) {
		//printStacktrace();
		 fn(id, mass);
	}
gdfloat cgo_callfn_GDExtensionSpxPhysicGetMass(const GDExtensionSpxPhysicGetMass fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxPhysicAddForce(const GDExtensionSpxPhysicAddForce fn, gdint id, gdvec2 force) {
		//printStacktrace();
		 fn(id, force);
	}
void cgo_callfn_GDExtensionSpxPhysicAddImpulse(const GDExtensionSpxPhysicAddImpulse fn, gdint id, gdvec2 impulse) {
		//printStacktrace();
		 fn(id, impulse);
	}
void cgo_callfn_GDExtensionSpxPhysicSetCollisionLayer(const GDExtensionSpxPhysicSetCollisionLayer fn, gdint id, gdint layer) {
		//printStacktrace();
		 fn(id, layer);
	}
gdint cgo_callfn_GDExtensionSpxPhysicGetCollisionLayer(const GDExtensionSpxPhysicGetCollisionLayer fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxPhysicSetCollisionMask(const GDExtensionSpxPhysicSetCollisionMask fn, gdint id, gdint mask) {
		//printStacktrace();
		 fn(id, mask);
	}
gdint cgo_callfn_GDExtensionSpxPhysicGetCollisionMask(const GDExtensionSpxPhysicGetCollisionMask fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
gdint cgo_callfn_GDExtensionSpxPhysicGetColliderType(const GDExtensionSpxPhysicGetColliderType fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxPhysicAddColliderRect(const GDExtensionSpxPhysicAddColliderRect fn, gdint id, gdvec2 center, gdvec2 size) {
		//printStacktrace();
		 fn(id, center, size);
	}
void cgo_callfn_GDExtensionSpxPhysicAddColliderCircle(const GDExtensionSpxPhysicAddColliderCircle fn, gdint id, gdvec2 center, gdfloat radius) {
		//printStacktrace();
		 fn(id, center, radius);
	}
void cgo_callfn_GDExtensionSpxPhysicAddColliderCapsule(const GDExtensionSpxPhysicAddColliderCapsule fn, gdint id, gdvec2 center, gdvec2 size) {
		//printStacktrace();
		 fn(id, center, size);
	}
void cgo_callfn_GDExtensionSpxPhysicSetTrigger(const GDExtensionSpxPhysicSetTrigger fn, gdint id, gdbool trigger) {
		//printStacktrace();
		 fn(id, trigger);
	}
gdbool cgo_callfn_GDExtensionSpxPhysicIsTrigger(const GDExtensionSpxPhysicIsTrigger fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxPhysicSetCollisionEnabled(const GDExtensionSpxPhysicSetCollisionEnabled fn, gdint id, gdbool enabled) {
		//printStacktrace();
		 fn(id, enabled);
	}
gdbool cgo_callfn_GDExtensionSpxPhysicIsCollisionEnabled(const GDExtensionSpxPhysicIsCollisionEnabled fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
gdint cgo_callfn_GDExtensionSpxSpriteCreateSprite(const GDExtensionSpxSpriteCreateSprite fn, gdstring path) {
		//printStacktrace();
		return fn(path);
	}
gdint cgo_callfn_GDExtensionSpxSpriteCloneSprite(const GDExtensionSpxSpriteCloneSprite fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
gdbool cgo_callfn_GDExtensionSpxSpriteDestroySprite(const GDExtensionSpxSpriteDestroySprite fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
gdbool cgo_callfn_GDExtensionSpxSpriteIsSpriteAlive(const GDExtensionSpxSpriteIsSpriteAlive fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxSpriteSetPosition(const GDExtensionSpxSpriteSetPosition fn, gdint id, gdvec2 pos) {
		//printStacktrace();
		 fn(id, pos);
	}
void cgo_callfn_GDExtensionSpxSpriteSetRotation(const GDExtensionSpxSpriteSetRotation fn, gdint id, gdvec2 rot) {
		//printStacktrace();
		 fn(id, rot);
	}
void cgo_callfn_GDExtensionSpxSpriteSetScale(const GDExtensionSpxSpriteSetScale fn, gdint id, gdvec2 scale) {
		//printStacktrace();
		 fn(id, scale);
	}
gdvec2 cgo_callfn_GDExtensionSpxSpriteGetPosition(const GDExtensionSpxSpriteGetPosition fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
gdvec2 cgo_callfn_GDExtensionSpxSpriteGetRotation(const GDExtensionSpxSpriteGetRotation fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
gdvec2 cgo_callfn_GDExtensionSpxSpriteGetScale(const GDExtensionSpxSpriteGetScale fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxSpriteSetColor(const GDExtensionSpxSpriteSetColor fn, gdint id, gdcolor gdcolor) {
		//printStacktrace();
		 fn(id, gdcolor);
	}
gdcolor cgo_callfn_GDExtensionSpxSpriteGetColor(const GDExtensionSpxSpriteGetColor fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxSpriteUpdateTexture(const GDExtensionSpxSpriteUpdateTexture fn, gdint id, gdstring path) {
		//printStacktrace();
		 fn(id, path);
	}
gdstring cgo_callfn_GDExtensionSpxSpriteGetTexture(const GDExtensionSpxSpriteGetTexture fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxSpriteSetVisible(const GDExtensionSpxSpriteSetVisible fn, gdint id, gdbool visible) {
		//printStacktrace();
		 fn(id, visible);
	}
gdbool cgo_callfn_GDExtensionSpxSpriteGetVisible(const GDExtensionSpxSpriteGetVisible fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxSpriteUpdateZIndex(const GDExtensionSpxSpriteUpdateZIndex fn, gdint id, gdint z) {
		//printStacktrace();
		 fn(id, z);
	}
gdint cgo_callfn_GDExtensionSpxUICreateButton(const GDExtensionSpxUICreateButton fn, gdstring path, gdrect rect, gdstring text) {
		//printStacktrace();
		return fn(path, rect, text);
	}
gdint cgo_callfn_GDExtensionSpxUICreateLabel(const GDExtensionSpxUICreateLabel fn, gdstring path, gdrect rect, gdstring text) {
		//printStacktrace();
		return fn(path, rect, text);
	}
gdint cgo_callfn_GDExtensionSpxUICreateImage(const GDExtensionSpxUICreateImage fn, gdstring path, gdrect rect, gdcolor gdcolor) {
		//printStacktrace();
		return fn(path, rect, gdcolor);
	}
gdint cgo_callfn_GDExtensionSpxUICreateSlider(const GDExtensionSpxUICreateSlider fn, gdstring path, gdrect rect, gdfloat value) {
		//printStacktrace();
		return fn(path, rect, value);
	}
gdint cgo_callfn_GDExtensionSpxUICreateToggle(const GDExtensionSpxUICreateToggle fn, gdstring path, gdrect rect, gdbool value) {
		//printStacktrace();
		return fn(path, rect, value);
	}
gdint cgo_callfn_GDExtensionSpxUICreateInput(const GDExtensionSpxUICreateInput fn, gdstring path, gdrect rect, gdstring text) {
		//printStacktrace();
		return fn(path, rect, text);
	}
gdint cgo_callfn_GDExtensionSpxUIGetType(const GDExtensionSpxUIGetType fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxUISetInteractable(const GDExtensionSpxUISetInteractable fn, gdint id, gdbool interactable) {
		//printStacktrace();
		 fn(id, interactable);
	}
gdbool cgo_callfn_GDExtensionSpxUIGetInteractable(const GDExtensionSpxUIGetInteractable fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxUISetText(const GDExtensionSpxUISetText fn, gdint id, gdstring text) {
		//printStacktrace();
		 fn(id, text);
	}
gdstring cgo_callfn_GDExtensionSpxUIGetText(const GDExtensionSpxUIGetText fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxUISetRect(const GDExtensionSpxUISetRect fn, gdint id, gdrect rect) {
		//printStacktrace();
		 fn(id, rect);
	}
gdrect cgo_callfn_GDExtensionSpxUIGetRect(const GDExtensionSpxUIGetRect fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxUISetColor(const GDExtensionSpxUISetColor fn, gdint id, gdcolor gdcolor) {
		//printStacktrace();
		 fn(id, gdcolor);
	}
gdcolor cgo_callfn_GDExtensionSpxUIGetColor(const GDExtensionSpxUIGetColor fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxUISetFontSize(const GDExtensionSpxUISetFontSize fn, gdint id, gdfloat size) {
		//printStacktrace();
		 fn(id, size);
	}
gdfloat cgo_callfn_GDExtensionSpxUIGetFontSize(const GDExtensionSpxUIGetFontSize fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxUISetVisible(const GDExtensionSpxUISetVisible fn, gdint id, gdbool visible) {
		//printStacktrace();
		 fn(id, visible);
	}
gdbool cgo_callfn_GDExtensionSpxUIGetVisible(const GDExtensionSpxUIGetVisible fn, gdint id) {
		//printStacktrace();
		return fn(id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnEngineStart(const GDExtensionSpxCallbackOnEngineStart fn) {
		//printStacktrace();
		 fn();
	}
void cgo_callfn_GDExtensionSpxCallbackOnEngineUpdate(const GDExtensionSpxCallbackOnEngineUpdate fn, gdfloat delta) {
		//printStacktrace();
		 fn(delta);
	}
void cgo_callfn_GDExtensionSpxCallbackOnEngineDestroy(const GDExtensionSpxCallbackOnEngineDestroy fn) {
		//printStacktrace();
		 fn();
	}
void cgo_callfn_GDExtensionSpxCallbackOnSpriteReady(const GDExtensionSpxCallbackOnSpriteReady fn, gdint id) {
		//printStacktrace();
		 fn(id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnSpriteUpdated(const GDExtensionSpxCallbackOnSpriteUpdated fn, gdint id) {
		//printStacktrace();
		 fn(id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnSpriteDestroyed(const GDExtensionSpxCallbackOnSpriteDestroyed fn, gdint id) {
		//printStacktrace();
		 fn(id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnMousePressed(const GDExtensionSpxCallbackOnMousePressed fn, gdint keyid) {
		//printStacktrace();
		 fn(keyid);
	}
void cgo_callfn_GDExtensionSpxCallbackOnMouseReleased(const GDExtensionSpxCallbackOnMouseReleased fn, gdint keyid) {
		//printStacktrace();
		 fn(keyid);
	}
void cgo_callfn_GDExtensionSpxCallbackOnKeyPressed(const GDExtensionSpxCallbackOnKeyPressed fn, gdint keyid) {
		//printStacktrace();
		 fn(keyid);
	}
void cgo_callfn_GDExtensionSpxCallbackOnKeyReleased(const GDExtensionSpxCallbackOnKeyReleased fn, gdint keyid) {
		//printStacktrace();
		 fn(keyid);
	}
void cgo_callfn_GDExtensionSpxCallbackOnActionPressed(const GDExtensionSpxCallbackOnActionPressed fn, gdstring action_name) {
		//printStacktrace();
		 fn(action_name);
	}
void cgo_callfn_GDExtensionSpxCallbackOnActionJustPressed(const GDExtensionSpxCallbackOnActionJustPressed fn, gdstring action_name) {
		//printStacktrace();
		 fn(action_name);
	}
void cgo_callfn_GDExtensionSpxCallbackOnActionJustReleased(const GDExtensionSpxCallbackOnActionJustReleased fn, gdstring action_name) {
		//printStacktrace();
		 fn(action_name);
	}
void cgo_callfn_GDExtensionSpxCallbackOnAxisChanged(const GDExtensionSpxCallbackOnAxisChanged fn, gdstring action_name, gdfloat value) {
		//printStacktrace();
		 fn(action_name, value);
	}
void cgo_callfn_GDExtensionSpxCallbackOnCollisionEnter(const GDExtensionSpxCallbackOnCollisionEnter fn, gdint self_id, gdint other_id) {
		//printStacktrace();
		 fn(self_id, other_id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnCollisionStay(const GDExtensionSpxCallbackOnCollisionStay fn, gdint self_id, gdint other_id) {
		//printStacktrace();
		 fn(self_id, other_id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnCollisionExit(const GDExtensionSpxCallbackOnCollisionExit fn, gdint self_id, gdint other_id) {
		//printStacktrace();
		 fn(self_id, other_id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnTriggerEnter(const GDExtensionSpxCallbackOnTriggerEnter fn, gdint self_id, gdint other_id) {
		//printStacktrace();
		 fn(self_id, other_id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnTriggerStay(const GDExtensionSpxCallbackOnTriggerStay fn, gdint self_id, gdint other_id) {
		//printStacktrace();
		 fn(self_id, other_id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnTriggerExit(const GDExtensionSpxCallbackOnTriggerExit fn, gdint self_id, gdint other_id) {
		//printStacktrace();
		 fn(self_id, other_id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnUIPressed(const GDExtensionSpxCallbackOnUIPressed fn, gdint id) {
		//printStacktrace();
		 fn(id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnUIReleased(const GDExtensionSpxCallbackOnUIReleased fn, gdint id) {
		//printStacktrace();
		 fn(id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnUIHovered(const GDExtensionSpxCallbackOnUIHovered fn, gdint id) {
		//printStacktrace();
		 fn(id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnUIClicked(const GDExtensionSpxCallbackOnUIClicked fn, gdint id) {
		//printStacktrace();
		 fn(id);
	}
void cgo_callfn_GDExtensionSpxCallbackOnUIToggle(const GDExtensionSpxCallbackOnUIToggle fn, gdint id, gdbool is_on) {
		//printStacktrace();
		 fn(id, is_on);
	}
void cgo_callfn_GDExtensionSpxCallbackOnUITextChanged(const GDExtensionSpxCallbackOnUITextChanged fn, gdint id, gdstring text) {
		//printStacktrace();
		 fn(id, text);
	}
