/*------------------------------------------------------------------------------
//   This code was generated by template ffi_gdextension_interface.go.tmpl.
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated. Any updates should be done in
//   "ffi_gdextension_interface.go.tmpl" so they can be included in the generated
//   code.
//----------------------------------------------------------------------------*/
package engine

type IAudioMgr interface {
	PlayAudio(path string)
	SetAudioVolume(volume float64)
	GetAudioVolume() float64 
	IsMusicPlaying() bool 
	PlayMusic(path string)
	SetMusicVolume(volume float64)
	GetMusicVolume() float64 
	PauseMusic()
	ResumeMusic()
	GetMusicTimer() float64 
	SetMusicTimer(time float64) 
}

type IInputMgr interface {
	GetMousePos() Vec2 
	GetMouseState(mouse_id int64) bool 
	GetKeyState(key int64) int64 
	GetAxis(axis string) float64 
	IsActionPressed(action string) bool 
	IsActionJustPressed(action string) bool 
	IsActionJustReleased(action string) bool  
}

type IPhysicMgr interface {
	SetGravity(gravity float64)
	GetGravity() float64 
	SetVelocity(obj Object, velocity Vec2)
	GetVelocity(obj Object) Vec2 
	SetMass(obj Object, mass float64)
	GetMass(obj Object) float64 
	AddForce(obj Object, force Vec2)
	AddImpulse(obj Object, impulse Vec2)
	SetCollisionLayer(obj Object, layer int64)
	GetCollisionLayer(obj Object) int64 
	SetCollisionMask(obj Object, mask int64)
	GetCollisionMask(obj Object) int64 
	GetColliderType(obj Object) int64 
	AddColliderRect(obj Object, center Vec2, size Vec2)
	AddColliderCircle(obj Object, center Vec2, radius float64)
	AddColliderCapsule(obj Object, center Vec2, size Vec2)
	SetTrigger(obj Object, trigger bool)
	IsTrigger(obj Object) bool 
	SetCollisionEnabled(obj Object, enabled bool)
	IsCollisionEnabled(obj Object) bool  
}

type ISpriteMgr interface {
	CreateSprite(path string) Object 
	CloneSprite(obj Object) Object 
	DestroySprite(obj Object) bool 
	IsSpriteAlive(obj Object) bool 
	SetPosition(obj Object, pos Vec2)
	SetRotation(obj Object, rot float64)
	SetScale(obj Object, scale Vec2)
	GetPosition(obj Object) Vec2 
	GetRotation(obj Object) float64 
	GetScale(obj Object) Vec2 
	SetColor(obj Object, color Color)
	GetColor(obj Object) Color 
	UpdateTexture(obj Object, path string)
	GetTexture(obj Object) string 
	SetVisible(obj Object, visible bool)
	GetVisible(obj Object) bool 
	UpdateZIndex(obj Object, z int64) 
}

type IUiMgr interface {
	CreateButton(path string, rect Rect2, text string) int64 
	CreateLabel(path string, rect Rect2, text string) int64 
	CreateImage(path string, rect Rect2, color Color) int64 
	CreateSlider(path string, rect Rect2, value float64) int64 
	CreateToggle(path string, rect Rect2, value bool) int64 
	CreateInput(path string, rect Rect2, text string) int64 
	GetType(obj Object) int64 
	SetInteractable(obj Object, interactable bool)
	GetInteractable(obj Object) bool 
	SetText(obj Object, text string)
	GetText(obj Object) string 
	SetRect(obj Object, rect Rect2)
	GetRect(obj Object) Rect2 
	SetColor(obj Object, color Color)
	GetColor(obj Object) Color 
	SetFontSize(obj Object, size float64)
	GetFontSize(obj Object) float64 
	SetVisible(obj Object, visible bool)
	GetVisible(obj Object) bool  
}


